countries= (("","Select Nationality"),('Afghan', 'Afghan'), ('Albanian', 'Albanian'), ('Algerian', 'Algerian'), ('American', 'American'), ('Andorran', 'Andorran'), ('Angolan', 'Angolan'), ('Antiguans', 'Antiguans'), ('Argentinean', 'Argentinean'), ('Armenian', 'Armenian'), ('Australian', 'Australian'), ('Austrian', 'Austrian'), ('Azerbaijani', 'Azerbaijani'), ('Bahamian', 'Bahamian'), ('Bahraini', 'Bahraini'), ('Bangladeshi', 'Bangladeshi'), ('Barbadian', 'Barbadian'), ('Barbudans', 'Barbudans'), ('Batswana', 'Batswana'), ('Belarusian', 'Belarusian'), ('Belgian', 'Belgian'), ('Belizean', 'Belizean'), ('Beninese', 'Beninese'), ('Bhutanese', 'Bhutanese'), ('Bolivian', 'Bolivian'), ('Bosnian', 'Bosnian'), ('Brazilian', 'Brazilian'), ('British', 'British'), ('Bruneian', 'Bruneian'), ('Bulgarian', 'Bulgarian'), ('Burkinabe', 'Burkinabe'), ('Burmese', 'Burmese'), ('Burundian', 'Burundian'), ('Cambodian', 'Cambodian'), ('Cameroonian', 'Cameroonian'), ('Canadian', 'Canadian'), ('Cape Verdean', 'Cape Verdean'), ('Central African', 'Central African'), ('Chadian', 'Chadian'), ('Chilean', 'Chilean'), ('Chinese', 'Chinese'), ('Colombian', 'Colombian'), ('Comoran', 'Comoran'), ('Congolese', 'Congolese'), ('Costa Rican', 'Costa Rican'), ('Croatian', 'Croatian'), ('Cuban', 'Cuban'), ('Cypriot', 'Cypriot'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Djibouti', 'Djibouti'), ('Dominican', 'Dominican'), ('Dutch', 'Dutch'), ('Dutchman', 'Dutchman'), ('Dutchwoman', 'Dutchwoman'), ('East Timorese', 'East Timorese'), ('Ecuadorean', 'Ecuadorean'), ('Egyptian', 'Egyptian'), ('Emirian', 'Emirian'), ('Equatorial Guinean', 'Equatorial Guinean'), ('Eritrean', 'Eritrean'), ('Estonian', 'Estonian'), ('Ethiopian', 'Ethiopian'), ('Fijian', 'Fijian'), ('Filipino', 'Filipino'), ('Finnish', 'Finnish'), ('French', 'French'), ('Gabonese', 'Gabonese'), ('Gambian', 'Gambian'), ('Georgian', 'Georgian'), ('German', 'German'), ('Ghanaian', 'Ghanaian'), ('Greek', 'Greek'), ('Grenadian', 'Grenadian'), ('Guatemalan', 'Guatemalan'), ('Guinea-Bissauan', 'Guinea-Bissauan'), ('Guinean', 'Guinean'), ('Guyanese', 'Guyanese'), ('Haitian', 'Haitian'), ('Herzegovinian', 'Herzegovinian'), ('Honduran', 'Honduran'), ('Hungarian', 'Hungarian'), ('I-Kiribati', 'I-Kiribati'), ('Icelander', 'Icelander'), ('Indian', 'Indian'), ('Indonesian', 'Indonesian'), ('Iranian', 'Iranian'), ('Iraqi', 'Iraqi'), ('Irish', 'Irish'), ('Israeli', 'Israeli'), ('Italian', 'Italian'), ('Ivorian', 'Ivorian'), ('Jamaican', 'Jamaican'), ('Japanese', 'Japanese'), ('Jordanian', 'Jordanian'), ('Kazakhstani', 'Kazakhstani'), ('Kenyan', 'Kenyan'), ('Kittian and Nevisian', 'Kittian and Nevisian'), ('Kuwaiti', 'Kuwaiti'), ('Kyrgyz', 'Kyrgyz'), ('Laotian', 'Laotian'), ('Latvian', 'Latvian'), ('Lebanese', 'Lebanese'), ('Liberian', 'Liberian'), ('Libyan', 'Libyan'), ('Liechtensteiner', 'Liechtensteiner'), ('Lithuanian', 'Lithuanian'), ('Luxembourger', 'Luxembourger'), ('Macedonian', 'Macedonian'), ('Malagasy', 'Malagasy'), ('Malawian', 'Malawian'), ('Malaysian', 'Malaysian'), ('Maldivan', 'Maldivan'), ('Malian', 'Malian'), ('Maltese', 'Maltese'), ('Marshallese', 'Marshallese'), ('Mauritanian', 'Mauritanian'), ('Mauritian', 'Mauritian'), ('Mexican', 'Mexican'), ('Micronesian', 'Micronesian'), ('Moldovan', 'Moldovan'), ('Monacan', 'Monacan'), ('Mongolian', 'Mongolian'), ('Moroccan', 'Moroccan'), ('Mosotho', 'Mosotho'), ('Motswana', 'Motswana'), ('Mozambican', 'Mozambican'), ('Namibian', 'Namibian'), ('Nauruan', 'Nauruan'), ('Nepalese', 'Nepalese'), ('Netherlander', 'Netherlander'), ('New Zealander', 'New Zealander'), ('Ni-Vanuatu', 'Ni-Vanuatu'), ('Nicaraguan', 'Nicaraguan'), ('Nigerian', 'Nigerian'), ('Nigerien', 'Nigerien'), ('North Korean', 'North Korean'), ('Northern Irish', 'Northern Irish'), ('Norwegian', 'Norwegian'), ('Omani', 'Omani'), ('Pakistani', 'Pakistani'), ('Palauan', 'Palauan'), ('Panamanian', 'Panamanian'), ('Papua New Guinean', 'Papua New Guinean'), ('Paraguayan', 'Paraguayan'), ('Peruvian', 'Peruvian'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Qatari', 'Qatari'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Rwandan', 'Rwandan'), ('Saint Lucian', 'Saint Lucian'), ('Salvadoran', 'Salvadoran'), ('Samoan', 'Samoan'), ('San Marinese', 'San Marinese'), ('Sao Tomean', 'Sao Tomean'), ('Saudi', 'Saudi'), ('Scottish', 'Scottish'), ('Senegalese', 'Senegalese'), ('Serbian', 'Serbian'), ('Seychellois', 'Seychellois'), ('Sierra Leonean', 'Sierra Leonean'), ('Singaporean', 'Singaporean'), ('Slovakian', 'Slovakian'), ('Slovenian', 'Slovenian'), ('Solomon Islander', 'Solomon Islander'), ('Somali', 'Somali'), ('South African', 'South African'), ('South Korean', 'South Korean'), ('Spanish', 'Spanish'), ('Sri Lankan', 'Sri Lankan'), ('Sudanese', 'Sudanese'), ('Surinamer', 'Surinamer'), ('Swazi', 'Swazi'), ('Swedish', 'Swedish'), ('Swiss', 'Swiss'), ('Syrian', 'Syrian'), ('Taiwanese', 'Taiwanese'), ('Tajik', 'Tajik'), ('Tanzanian', 'Tanzanian'), ('Thai', 'Thai'), ('Togolese', 'Togolese'), ('Tongan', 'Tongan'), ('Trinidadian or Tobagonian', 'Trinidadian or Tobagonian'), ('Tunisian', 'Tunisian'), ('Turkish', 'Turkish'), ('Tuvaluan', 'Tuvaluan'), ('Ugandan', 'Ugandan'), ('Ukrainian', 'Ukrainian'), ('Uruguayan', 'Uruguayan'), ('Uzbekistani', 'Uzbekistani'), ('Venezuelan', 'Venezuelan'), ('Vietnamese', 'Vietnamese'), ('Welsh', 'Welsh'), ('Yemenite', 'Yemenite'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean'))
hospital_departments=['Radiology','Laboratory']
user_levels= (('CEO','CEO'),('Medical Director','Medical Director'),('Finance Manager','Finance Manager'),('Commercial Manager','Commercial Manager'),
    ('Radiographer','Radiographer'),('Sonographer','Sonographer'),('Lab Scientist','Lab Scientist'),
    ('Pharmacist','Pharmacist'),('Nurse','Nurse'),('Receptionist','Receptionist'),('Secretary','Secretary'))

# this is used in Patients Registration Form for DateField dateformat 
DATE_INPUT_FORMATS=['%d-%m-%Y','%Y-%m-%d']

investigations_types=(('X-RAY','X-RAY'),('LABORATORY INVESTIGATION','LABORATORY INVESTIGATION'))

med_dent_types=(('PAST MEDICAL HISTORY','PAST MEDICAL HISTORY'),('DRUG HISTORY','DRUG HISTORY'),('DENTAL HISTORY','DENTAL HISTORY'),
    ('FAMILY HISTORY','FAMILY HISTORY'),('ORAL HABITS','ORAL HABITS'),('SOCIAL HISTORY','SOCIAL HISTORY'),('ALLERGIES','ALLERGIES'))
    
#     return  (
#     ("","Select Nationality"),
#     ('AF', 'AFGHANISTAN'),
#     ('AL', 'ALBANIA'),
#     ('DZ', 'ALGERIA'),
#     ('AS', 'AMERICAN SAMOA'),
#     ('AD', 'ANDORRA'),
#     ('AO', 'ANGOLA'),
#     ('AI', 'ANGUILLA'),
#     ('AQ', 'ANTARCTICA'),
#     ('AG', 'ANTIGUA AND BARBUDA'),
#     ('AR', 'ARGENTINA'),
#     ('AM', 'ARMENIA'),
#     ('AW', 'ARUBA'),
#     ('AU', 'AUSTRALIA'),
#     ('AT', 'AUSTRIA'),
#     ('AZ', 'AZERBAIJAN'),
#     ('BS', 'BAHAMAS'),
#     ('BH', 'BAHRAIN'),
#     ('BD', 'BANGLADESH'),
#     ('BB', 'BARBADOS'),
#     ('BY', 'BELARUS'),
#     ('BE', 'BELGIUM'),
#     ('BZ', 'BELIZE'),
#     ('BJ', 'BENIN'),
#     ('BM', 'BERMUDA'),
#     ('BT', 'BHUTAN'),
#     ('BO', 'BOLIVIA'),
#     ('BA', 'BOSNIA AND HERZEGOVINA'),
#     ('BW', 'BOTSWANA'),
#     ('BV', 'BOUVET ISLAND'),
#     ('BR', 'BRAZIL'),
#     ('IO', 'BRITISH INDIAN OCEAN TERRITORY'),
#     ('BN', 'BRUNEI DARUSSALAM'),
#     ('BG', 'BULGARIA'),
#     ('BF', 'BURKINA FASO'),
#     ('BI', 'BURUNDI'),
#     ('KH', 'CAMBODIA'),
#     ('CM', 'CAMEROON'),
#     ('CA', 'CANADA'),
#     ('CV', 'CAPE VERDE'),
#     ('KY', 'CAYMAN ISLANDS'),
#     ('CF', 'CENTRAL AFRICAN REPUBLIC'),
#     ('TD', 'CHAD'),
#     ('CL', 'CHILE'),
#     ('CN', 'CHINA'),
#     ('CX', 'CHRISTMAS ISLAND'),
#     ('CC', 'COCOS (KEELING) ISLANDS'),
#     ('CO', 'COLOMBIA'),
#     ('KM', 'COMOROS'),
#     ('CG', 'CONGO'),
#     ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF'),
#     ('CK', 'COOK ISLANDS'),
#     ('CR', 'COSTA RICA'),
#     ('CI', "CÃ”TE D'IVOIRE"),
#     ('HR', 'CROATIA'),
#     ('CU', 'CUBA'),
#     ('CY', 'CYPRUS'),
#     ('CZ', 'CZECH REPUBLIC'),
#     ('DK', 'DENMARK'),
#     ('DJ', 'DJIBOUTI'),
#     ('DM', 'DOMINICA'),
#     ('DO', 'DOMINICAN REPUBLIC'),
#     ('EC', 'ECUADOR'),
#     ('EG', 'EGYPT'),
#     ('SV', 'EL SALVADOR'),
#     ('GQ', 'EQUATORIAL GUINEA'),
#     ('ER', 'ERITREA'),
#     ('EE', 'ESTONIA'),
#     ('ET', 'ETHIOPIA'),
#     ('FK', 'FALKLAND ISLANDS (MALVINAS)'),
#     ('FO', 'FAROE ISLANDS'),
#     ('FJ', 'FIJI'),
#     ('FI', 'FINLAND'),
#     ('FR', 'FRANCE'),
#     ('GF', 'FRENCH GUIANA'),
#     ('PF', 'FRENCH POLYNESIA'),
#     ('TF', 'FRENCH SOUTHERN TERRITORIES'),
#     ('GA', 'GABON'),
#     ('GM', 'GAMBIA'),
#     ('GE', 'GEORGIA'),
#     ('DE', 'GERMANY'),
#     ('GH', 'GHANA'),
#     ('GI', 'GIBRALTAR'),
#     ('GR', 'GREECE'),
#     ('GL', 'GREENLAND'),
#     ('GD', 'GRENADA'),
#     ('GP', 'GUADELOUPE'),
#     ('GU', 'GUAM'),
#     ('GT', 'GUATEMALA'),
#     ('GN', 'GUINEA'),
#     ('GW', 'GUINEA'),
#     ('GY', 'GUYANA'),
#     ('HT', 'HAITI'),
#     ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS'),
#     ('HN', 'HONDURAS'),
#     ('HK', 'HONG KONG'),
#     ('HU', 'HUNGARY'),
#     ('IS', 'ICELAND'),
#     ('IN', 'INDIA'),
#     ('ID', 'INDONESIA'),
#     ('IR', 'IRAN, ISLAMIC REPUBLIC OF'),
#     ('IQ', 'IRAQ'),
#     ('IE', 'IRELAND'),
#     ('IL', 'ISRAEL'),
#     ('IT', 'ITALY'),
#     ('JM', 'JAMAICA'),
#     ('JP', 'JAPAN'),
#     ('JO', 'JORDAN'),
#     ('KZ', 'KAZAKHSTAN'),
#     ('KE', 'KENYA'),
#     ('KI', 'KIRIBATI'),
#     ('KP', "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
#     ('KR', 'KOREA, REPUBLIC OF'),
#     ('KW', 'KUWAIT'),
#     ('KG', 'KYRGYZSTAN'),
#     ('LA', "LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
#     ('LV', 'LATVIA'),
#     ('LB', 'LEBANON'),
#     ('LS', 'LESOTHO'),
#     ('LR', 'LIBERIA'),
#     ('LY', 'LIBYAN ARAB JAMAHIRIYA'),
#     ('LI', 'LIECHTENSTEIN'),
#     ('LT', 'LITHUANIA'),
#     ('LU', 'LUXEMBOURG'),
#     ('MO', 'MACAO'),
#     ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'),
#     ('MG', 'MADAGASCAR'),
#     ('MW', 'MALAWI'),
#     ('MY', 'MALAYSIA'),
#     ('MV', 'MALDIVES'),
#     ('ML', 'MALI'),
#     ('MT', 'MALTA'),
#     ('MH', 'MARSHALL ISLANDS'),
#     ('MQ', 'MARTINIQUE'),
#     ('MR', 'MAURITANIA'),
#     ('MU', 'MAURITIUS'),
#     ('YT', 'MAYOTTE'),
#     ('MX', 'MEXICO'),
#     ('FM', 'MICRONESIA, FEDERATED STATES OF'),
#     ('MD', 'MOLDOVA, REPUBLIC OF'),
#     ('MC', 'MONACO'),
#     ('MN', 'MONGOLIA'),
#     ('MS', 'MONTSERRAT'),
#     ('MA', 'MOROCCO'),
#     ('MZ', 'MOZAMBIQUE'),
#     ('MM', 'MYANMAR'),
#     ('NA', 'NAMIBIA'),
#     ('NR', 'NAURU'),
#     ('NP', 'NEPAL'),
#     ('NL', 'NETHERLANDS'),
#     ('AN', 'NETHERLANDS ANTILLES'),
#     ('NC', 'NEW CALEDONIA'),
#     ('NZ', 'NEW ZEALAND'),
#     ('NI', 'NICARAGUA'),
#     ('NE', 'NIGER'),
#     ('NG', 'NIGERIA'),
#     ('NU', 'NIUE'),
#     ('NF', 'NORFOLK ISLAND'),
#     ('MP', 'NORTHERN MARIANA ISLANDS'),
#     ('NO', 'NORWAY'),
#     ('OM', 'OMAN'),
#     ('PK', 'PAKISTAN'),
#     ('PW', 'PALAU'),
#     ('PS', 'PALESTINIAN TERRITORY, OCCUPIED'),
#     ('PA', 'PANAMA'),
#     ('PG', 'PAPUA NEW GUINEA'),
#     ('PY', 'PARAGUAY'),
#     ('PE', 'PERU'),
#     ('PH', 'PHILIPPINES'),
#     ('PN', 'PITCAIRN'),
#     ('PL', 'POLAND'),
#     ('PT', 'PORTUGAL'),
#     ('PR', 'PUERTO RICO'),
#     ('QA', 'QATAR'),
#     ('RE', 'RÃ‰UNION'),
#     ('RO', 'ROMANIA'),
#     ('RU', 'RUSSIAN FEDERATION'),
#     ('RW', 'RWANDA'),
#     ('SH', 'SAINT HELENA'),
#     ('KN', 'SAINT KITTS AND NEVIS'),
#     ('LC', 'SAINT LUCIA'),
#     ('PM', 'SAINT PIERRE AND MIQUELON'),
#     ('VC', 'SAINT VINCENT AND THE GRENADINES'),
#     ('WS', 'SAMOA'),
#     ('SM', 'SAN MARINO'),
#     ('ST', 'SAO TOME AND PRINCIPE'),
#     ('SA', 'SAUDI ARABIA'),
#     ('SN', 'SENEGAL'),
#     ('CS', 'SERBIA AND MONTENEGRO'),
#     ('SC', 'SEYCHELLES'),
#     ('SL', 'SIERRA LEONE'),
#     ('SG', 'SINGAPORE'),
#     ('SK', 'SLOVAKIA'),
#     ('SI', 'SLOVENIA'),
#     ('SB', 'SOLOMON ISLANDS'),
#     ('SO', 'SOMALIA'),
#     ('ZA', 'SOUTH AFRICA'),
#     ('GS', 'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS'),
#     ('ES', 'SPAIN'),
#     ('LK', 'SRI LANKA'),
#     ('SD', 'SUDAN'),
#     ('SR', 'SURINAME'),
#     ('SJ', 'SVALBARD AND JAN MAYEN'),
#     ('SZ', 'SWAZILAND'),
#     ('SE', 'SWEDEN'),
#     ('CH', 'SWITZERLAND'),
#     ('SY', 'SYRIAN ARAB REPUBLIC'),
#     ('TW', 'TAIWAN, PROVINCE OF CHINA'),
#     ('TJ', 'TAJIKISTAN'),
#     ('TZ', 'TANZANIA, UNITED REPUBLIC OF'),
#     ('TH', 'THAILAND'),
#     ('TL', 'TIMOR'),
#     ('TG', 'TOGO'),
#     ('TK', 'TOKELAU'),
#     ('TO', 'TONGA'),
#     ('TT', 'TRINIDAD AND TOBAGO'),
#     ('TN', 'TUNISIA'),
#     ('TR', 'TURKEY'),
#     ('TM', 'TURKMENISTAN'),
#     ('TC', 'TURKS AND CAICOS ISLANDS'),
#     ('TV', 'TUVALU'),
#     ('UG', 'UGANDA'),
#     ('UA', 'UKRAINE'),
#     ('AE', 'UNITED ARAB EMIRATES'),
#     ('GB', 'UNITED KINGDOM'),
#     ('US', 'UNITED STATES'),
#     ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS'),
#     ('UY', 'URUGUAY'),
#     ('UZ', 'UZBEKISTAN'),
#     ('VU', 'VANUATU'),
#     ('VN', 'VIET NAM'),
#     ('VG', 'VIRGIN ISLANDS, BRITISH'),
#     ('VI', 'VIRGIN ISLANDS, U.S.'),
#     ('WF', 'WALLIS AND FUTUNA'),
#     ('EH', 'WESTERN SAHARA'),
#     ('YE', 'YEMEN'),
#     ('ZW', 'ZIMBABWE')
# )
    