# Generated by Django 4.1 on 2023-03-24 09:10

import I_CARE.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Preferred_Date', models.DateField()),
                ('Message', models.TextField()),
                ('Preferred_Time', models.CharField(max_length=20)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Approval_Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Min_Amount', models.DecimalField(decimal_places=2, max_digits=50, unique=True)),
                ('Max_Amount', models.DecimalField(decimal_places=2, max_digits=50, unique=True)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Requisition Authorizer',
                'db_table': 'approval_authority',
            },
        ),
        migrations.CreateModel(
            name='Business_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_Name', models.CharField(default='FRAMADA DENTAL CLINIC', max_length=100, null=True)),
                ('Bus_Name_Abbr', models.CharField(default='FRAMADA', max_length=100, null=True)),
                ('GPS_Address', models.TextField(default='AG-26572-2726, SANTASI-KUMASI')),
                ('City', models.CharField(default='GH-Kumasi', max_length=100, null=True)),
                ('Postal', models.CharField(default='P.O.BOX 9981 ADUM-KSM', max_length=50, null=True)),
                ('App_Tel', models.CharField(default='+233', max_length=15)),
                ('Gen_Tel', models.CharField(default='+233', max_length=30)),
                ('Email', models.CharField(default='info@framadadentalclinic.com', max_length=100)),
                ('Facebook', models.URLField(default='https://fb.com')),
                ('Instagram', models.URLField(default='https://instagram.com')),
                ('Linkedin', models.URLField(default='https://linkedin.com')),
                ('Twitter', models.URLField(default='https://twitter.com')),
                ('Youtube', models.URLField(default='https://youtube.com')),
                ('Website', models.URLField(default='https://framada.pythonanywhere.com')),
                ('Sms_Api_Key', models.CharField(default='OkZRZlp1T2lBMHdPQnQ5YVc=', max_length=200)),
                ('Web_Logo', models.ImageField(blank=True, default='Logo', null=True, upload_to=I_CARE.models.business_file_path)),
                ('Footer_Logo', models.ImageField(blank=True, default='Logo', null=True, upload_to=I_CARE.models.business_file_path)),
                ('Fav_Icon', models.ImageField(blank=True, default='Logo', null=True, upload_to=I_CARE.models.business_file_path)),
            ],
            options={
                'verbose_name': 'Business Detail',
                'db_table': 'business_info',
            },
        ),
        migrations.CreateModel(
            name='Consulting_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'consulting_room',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'insurance',
            },
        ),
        migrations.CreateModel(
            name='Journal_History_Checker',
            fields=[
                ('Trans_Id', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('Cashier', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'journal_history_checker',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modality', models.CharField(max_length=50, unique=True)),
                ('Acronym', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'modalitie',
                'db_table': 'modalities',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Id', models.CharField(max_length=50, unique=True)),
                ('Profile', models.ImageField(blank=True, default=I_CARE.models.default_static_image_path, null=True, upload_to=I_CARE.models.patients_profile_path)),
                ('First_Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('DOB', models.DateField(default=django.utils.timezone.now)),
                ('Age', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Residence', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=15)),
                ('Emergency_Tel', models.CharField(max_length=15, null=True)),
                ('Occupation', models.CharField(default='None', max_length=100)),
                ('Email', models.EmailField(default='someone@here.com', max_length=254)),
                ('Date_Joined', models.DateField()),
                ('Last_Visit', models.DateTimeField()),
                ('Insurance_Id', models.CharField(default='xxx-xxxx-xxx', max_length=50)),
                ('Balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Status', models.CharField(default='Waiting', max_length=20)),
                ('Time', models.TimeField(auto_now=True)),
                ('Insurance_Type', models.ForeignKey(db_column='Insurance_Type', null=True, on_delete=django.db.models.deletion.CASCADE, to='I_CARE.insurance')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Patients_Checker',
            fields=[
                ('Patient_Id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Reg_Date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'patients_checker',
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Procedure', models.CharField(max_length=100)),
                ('Charge', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Tag', models.CharField(choices=[('Radiology', 'Radiology'), ('Laboratory', 'Laboratory')], max_length=50)),
                ('Modality', models.ForeignKey(db_column='Modality', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.modalities')),
            ],
            options={
                'verbose_name': 'Procedure',
                'db_table': 'procedures',
            },
        ),
        migrations.CreateModel(
            name='Referring_Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_Name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Referring Facilitie',
                'db_table': 'referring_facilities',
            },
        ),
        migrations.CreateModel(
            name='Stocks_Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.CharField(max_length=50)),
                ('Product_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pos_stocks_checker',
            },
        ),
        migrations.CreateModel(
            name='Stocks_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=50, unique=True)),
                ('Date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_stocks_department',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=50, unique=True)),
                ('Contact', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_supplier',
            },
        ),
        migrations.CreateModel(
            name='Treatment_Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('Treatments', models.TextField()),
                ('Send_Alert', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'treatment_alert',
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(default='Bill Payment', max_length=50)),
                ('Status', models.CharField(default='Waiting', max_length=50)),
                ('Referring_Facility', models.CharField(default='None', max_length=100, null=True)),
                ('Referred_Doctor', models.CharField(default='None', max_length=50, null=True)),
                ('Treatment_Amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Paid_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Trans_Id', models.CharField(max_length=250)),
                ('Logger', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
                ('Patient_Id', models.ForeignKey(db_column='Patient_Id', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.patients')),
                ('Procedure', models.ForeignKey(db_column='Procedure', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.procedures')),
            ],
            options={
                'db_table': 'vitals',
            },
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ImageField(blank=True, default=I_CARE.models.default_static_image_path, null=True, upload_to=I_CARE.models.user_profile_path)),
                ('Gender', models.CharField(default='Male', max_length=10)),
                ('Contact', models.CharField(default='+233', max_length=50)),
                ('City', models.CharField(default='Kumasi', max_length=100)),
                ('Town', models.CharField(default='Santasi', max_length=100)),
                ('Address', models.TextField(default='Geo location')),
                ('About', models.TextField(default='Hi there, i am a doctor at Framada <(*v*)>')),
                ('Level', models.CharField(max_length=50)),
                ('User', models.OneToOneField(db_column='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'User Detail',
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('Product_Id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('Retail', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Whole_Sale', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Purchase', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Rprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('Wprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('Expiry_Date', models.DateField()),
                ('Invoice', models.CharField(default=None, max_length=50)),
                ('Department', models.ForeignKey(db_column='Department', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.stocks_department')),
                ('Suppliers', models.ForeignKey(db_column='Suppliers', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.supplier')),
            ],
            options={
                'db_table': 'pos_stocks',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Delivery_Timeline', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Total_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Approval_Status', models.CharField(default='Pending', max_length=50)),
                ('Delivery_Status', models.CharField(default='Pending', max_length=50)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
                ('Approval_Authority', models.ForeignKey(db_column='Approval_Authority', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.approval_authority')),
                ('Placeholder', models.ForeignKey(db_column='Placeholer', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.user_details')),
            ],
            options={
                'verbose_name': 'Requisition',
                'db_table': 'requisition',
            },
        ),
        migrations.CreateModel(
            name='Presenting_Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_Category', models.CharField(max_length=50)),
                ('Complaint_Type', models.CharField(max_length=50)),
                ('Complaints', models.TextField(default='None')),
                ('Docs_Complaints', models.TextField(default='None')),
                ('Tech_Report', models.FileField(blank=True, default=I_CARE.models.default_static_image_path, null=True, upload_to=I_CARE.models.patients_docs_path)),
                ('Tech_Report_Name', models.CharField(default='None', max_length=50)),
                ('Docs_Report', models.FileField(blank=True, default=I_CARE.models.default_static_image_path, null=True, upload_to=I_CARE.models.patients_docs_path)),
                ('Docs_Report_Name', models.CharField(default='None', max_length=50)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
                ('Docs_Instance', models.ForeignKey(db_column='Docs_Instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Docs_Instance_Logger', to='I_CARE.user_details')),
                ('Patient_Id', models.ForeignKey(db_column='Patient_Id', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.patients')),
                ('Tech_Instance', models.ForeignKey(db_column='Tech_Instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tech_Instance_Logger', to='I_CARE.user_details')),
                ('Vitals', models.ForeignKey(db_column='Vitals', null=True, on_delete=django.db.models.deletion.SET_NULL, to='I_CARE.vitals')),
            ],
            options={
                'db_table': 'presenting_complaints',
            },
        ),
        migrations.CreateModel(
            name='Payment_Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Treatment_Name', models.TextField()),
                ('Treatment_Amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Paid_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Note', models.TextField(default='Not Specified')),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
                ('Logger_Instance', models.ForeignKey(db_column='Logger_Instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='I_CARE.user_details')),
                ('Patient_Id', models.ForeignKey(db_column='Patient_Id', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.patients')),
            ],
            options={
                'db_table': 'payment_journal',
            },
        ),
        migrations.CreateModel(
            name='New_Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.CharField(max_length=50)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('Retail', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Whole_Sale', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Purchase', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Rprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('Wprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('Invoice', models.CharField(default=None, max_length=50)),
                ('Date', models.DateField(auto_now=True)),
                ('Department', models.ForeignKey(db_column='Department', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.stocks_department')),
                ('Suppliers', models.ForeignKey(db_column='Suppliers', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.supplier')),
            ],
            options={
                'db_table': 'pos_new_stocks',
            },
        ),
        migrations.CreateModel(
            name='Journal_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Payment_Type', models.CharField(max_length=20)),
                ('Approved_By', models.CharField(max_length=50)),
                ('Payment_Comment', models.TextField(null=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(auto_now=True)),
                ('Payment_Journal', models.ForeignKey(db_column='Payment_Journal', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.vitals')),
            ],
            options={
                'db_table': 'journal_history',
            },
        ),
        migrations.CreateModel(
            name='Drugs_Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Amount_Paid', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Frequency', models.CharField(max_length=50)),
                ('Others', models.CharField(default='Not Specified', max_length=10)),
                ('Duration', models.TextField(default='Not Specified')),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Sales_Status', models.CharField(default='Pending', max_length=20)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
                ('Drug_Id', models.ForeignKey(db_column='Drug_Id', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.stocks')),
                ('Journal_Id', models.ForeignKey(db_column='Journal_Id', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.payment_journal')),
                ('Logger_Instance', models.ForeignKey(db_column='Logger_Instance', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.user_details')),
                ('Patient_Id', models.ForeignKey(db_column='Patient_Id', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.patients')),
            ],
            options={
                'db_table': 'drugs_prescriptions',
            },
        ),
        migrations.CreateModel(
            name='Birthday_Wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('New_Age', models.IntegerField()),
                ('Delivery_Status', models.BooleanField(default=False)),
                ('Due_Date', models.DateField(auto_now=True)),
                ('Patient_Id', models.ForeignKey(db_column='Patient_Id', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.patients')),
            ],
            options={
                'db_table': 'birthday_wishes',
            },
        ),
        migrations.AddField(
            model_name='approval_authority',
            name='Authorizer',
            field=models.ForeignKey(db_column='Authorizer', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.user_details'),
        ),
    ]
