# Generated by Django 4.1 on 2023-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Procedure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
