# Generated by Django 4.1 on 2023-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0002_patients_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='Charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
            preserve_default=False,
        ),
    ]
