# Generated by Django 4.1 on 2023-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0003_procedures_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Email',
            field=models.EmailField(default='someone@here.come', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='Referring_Facility',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
