# Generated by Django 4.1 on 2023-03-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0004_patients_email_patients_referring_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referring_Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_Name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'referring_facilities',
            },
        ),
        migrations.AlterField(
            model_name='patients',
            name='Referring_Facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
