# Generated by Django 4.1 on 2023-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0005_referring_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Email',
            field=models.EmailField(default='someone@here.come', max_length=254),
        ),
    ]
