# Generated by Django 4.1 on 2023-03-16 19:00

import I_CARE.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0006_alter_patients_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presenting_complaints',
            old_name='Docs',
            new_name='Tech_Report',
        ),
        migrations.RenameField(
            model_name='presenting_complaints',
            old_name='Docs_Name',
            new_name='Tech_Report_Name',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Logger_Instance',
        ),
        migrations.AddField(
            model_name='presenting_complaints',
            name='Docs_Instance',
            field=models.ForeignKey(db_column='Docs_Instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Docs_Instance_Logger', to='I_CARE.user_details'),
        ),
        migrations.AddField(
            model_name='presenting_complaints',
            name='Docs_Report',
            field=models.FileField(blank=True, default=I_CARE.models.default_static_image_path, null=True, upload_to=I_CARE.models.patients_docs_path),
        ),
        migrations.AddField(
            model_name='presenting_complaints',
            name='Docs_Report_Name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='presenting_complaints',
            name='Tech_Instance',
            field=models.ForeignKey(db_column='Tech_Instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tech_Instance_Logger', to='I_CARE.user_details'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Email',
            field=models.EmailField(default='someone@here.com', max_length=254),
        ),
    ]
