# Generated by Django 4.1 on 2023-03-16 22:15

import I_CARE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0007_rename_docs_presenting_complaints_tech_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='Fav_Icon',
            field=models.ImageField(blank=True, default=I_CARE.models.default_static_image_path, null=True, upload_to=I_CARE.models.business_file_path),
        ),
        migrations.AddField(
            model_name='business_info',
            name='Footer_Logo',
            field=models.ImageField(blank=True, default=I_CARE.models.default_static_image_path, null=True, upload_to=I_CARE.models.business_file_path),
        ),
        migrations.AddField(
            model_name='business_info',
            name='Web_Logo',
            field=models.ImageField(blank=True, default=I_CARE.models.default_static_image_path, null=True, upload_to=I_CARE.models.business_file_path),
        ),
    ]
