# Generated by Django 4.1 on 2023-03-16 22:24

import I_CARE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0008_business_info_fav_icon_business_info_footer_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='Fav_Icon',
            field=models.ImageField(blank=True, null=True, upload_to=I_CARE.models.business_file_path),
        ),
        migrations.AlterField(
            model_name='business_info',
            name='Footer_Logo',
            field=models.ImageField(blank=True, null=True, upload_to=I_CARE.models.business_file_path),
        ),
        migrations.AlterField(
            model_name='business_info',
            name='Web_Logo',
            field=models.ImageField(blank=True, null=True, upload_to=I_CARE.models.business_file_path),
        ),
    ]
