# Generated by Django 4.1 on 2023-03-16 22:31

import I_CARE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0009_alter_business_info_fav_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='Fav_Icon',
            field=models.ImageField(blank=True, default='Logo', null=True, upload_to=I_CARE.models.business_file_path),
        ),
        migrations.AlterField(
            model_name='business_info',
            name='Footer_Logo',
            field=models.ImageField(blank=True, default='Logo', null=True, upload_to=I_CARE.models.business_file_path),
        ),
        migrations.AlterField(
            model_name='business_info',
            name='Web_Logo',
            field=models.ImageField(blank=True, default='Logo', null=True, upload_to=I_CARE.models.business_file_path),
        ),
    ]
