# Generated by Django 4.1 on 2023-03-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0013_patients_emergency_tel_patients_referred_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Occupation',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
