# Generated by Django 4.1 on 2023-03-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0014_alter_patients_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='Referred_Doctor',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='Referring_Facility',
        ),
    ]
