# Generated by Django 4.1 on 2023-03-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0015_remove_patients_referred_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Referred_Doctor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='Referring_Facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
