# Generated by Django 4.1 on 2023-03-19 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0018_alter_patients_emergency_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
