# Generated by Django 4.1 on 2023-03-19 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0019_alter_patients_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='Referred_Doctor',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='Referring_Facility',
        ),
        migrations.AlterField(
            model_name='patients',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
