# Generated by Django 4.1 on 2023-03-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0021_vitals_referred_doctor_vitals_referring_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='Procedure',
        ),
    ]
