# Generated by Django 4.1 on 2023-03-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0022_remove_patients_department_remove_patients_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='Referred_Doctor',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Referring_Facility',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
