# Generated by Django 4.1 on 2023-03-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0023_alter_vitals_referred_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modality', models.CharField(max_length=50, unique=True)),
                ('Acronym', models.TextField()),
            ],
            options={
                'db_table': 'modalities',
            },
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Department',
            field=models.CharField(default='Services', max_length=50),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Referred_Doctor',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='Referring_Facility',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
