# Generated by Django 4.1 on 2023-03-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0024_modalities_alter_vitals_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalities',
            name='Acronym',
            field=models.CharField(max_length=10),
        ),
    ]
