# Generated by Django 4.1 on 2023-03-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0025_alter_modalities_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='Modalitt',
            field=models.ForeignKey(db_column='Modality', default=1, on_delete=django.db.models.deletion.CASCADE, to='I_CARE.modalities'),
            preserve_default=False,
        ),
    ]
