# Generated by Django 4.1 on 2023-03-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0026_procedures_modalitt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedures',
            old_name='Modalitt',
            new_name='Modality',
        ),
    ]
