# Generated by Django 4.1 on 2023-03-20 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0027_rename_modalitt_procedures_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='Procedure',
            field=models.ForeignKey(db_column='Procedure', default=4, on_delete=django.db.models.deletion.CASCADE, to='I_CARE.procedures'),
            preserve_default=False,
        ),
    ]
