# Generated by Django 4.1 on 2023-03-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0028_vitals_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='Description',
        ),
    ]
