# Generated by Django 4.1 on 2023-03-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0029_remove_insurance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedures',
            name='Procedure',
            field=models.CharField(max_length=100),
        ),
    ]
