# Generated by Django 4.1 on 2023-03-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0030_alter_procedures_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedures',
            name='Tag',
            field=models.CharField(choices=[('Radiology', 'Radiology'), ('Laboratory', 'Laboratory')], max_length=50),
        ),
    ]
