# Generated by Django 4.1 on 2023-03-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0031_alter_procedures_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Complaint_Ans',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Duration_In',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Extraoral_Exam',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='General_Exam',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Intraoral_Exam',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Review_Date',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Systemic_Enquiry',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Treatment_Done',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Treatment_Other',
        ),
        migrations.RemoveField(
            model_name='presenting_complaints',
            name='Treatment_Plan',
        ),
    ]
