# Generated by Django 4.1 on 2023-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0032_remove_presenting_complaints_complaint_ans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenting_complaints',
            name='Docs_Complaints',
            field=models.TextField(default='None'),
        ),
    ]
