# Generated by Django 4.1 on 2023-03-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0033_presenting_complaints_docs_complaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Investigations',
        ),
        migrations.DeleteModel(
            name='Med_Dent_History',
        ),
        migrations.DeleteModel(
            name='React_Model',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Qualification',
        ),
    ]
