# Generated by Django 4.1 on 2023-03-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0034_delete_diagnosis_delete_investigations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Min_Amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Max_Amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('Authorizer', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_authority',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Delivery_Timeline', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Total_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('Delivery_Status', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(auto_now=True)),
                ('Approval_Authority', models.ForeignKey(db_column='Approval_Authority', on_delete=django.db.models.deletion.CASCADE, to='I_CARE.approval_authority')),
            ],
            options={
                'db_table': 'requisition',
            },
        ),
    ]
