# Generated by Django 4.1 on 2023-03-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0036_alter_approval_authority_authorizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval_authority',
            name='Max_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, unique=True),
        ),
        migrations.AlterField(
            model_name='approval_authority',
            name='Min_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, unique=True),
        ),
    ]
