# Generated by Django 4.1 on 2023-03-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0037_alter_approval_authority_max_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval_authority',
            options={'verbose_name': 'Authorities'},
        ),
    ]
