# Generated by Django 4.1 on 2023-03-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0038_alter_approval_authority_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_details',
            options={'verbose_name': 'User Details'},
        ),
    ]
