# Generated by Django 4.1 on 2023-03-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0039_alter_user_details_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval_authority',
            options={'verbose_name': 'Authoritie'},
        ),
        migrations.AlterModelOptions(
            name='user_details',
            options={'verbose_name': 'User Detail'},
        ),
    ]
