# Generated by Django 4.1 on 2023-03-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0040_alter_approval_authority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalities',
            options={'verbose_name': 'modalitie'},
        ),
        migrations.AlterModelOptions(
            name='requisition',
            options={'verbose_name': 'Requisition'},
        ),
    ]
