# Generated by Django 4.1 on 2023-03-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0042_alter_business_info_options_alter_procedures_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval_authority',
            options={'verbose_name': 'Requisition Approval Authorizer'},
        ),
        migrations.AlterField(
            model_name='requisition',
            name='Delivery_Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
