# Generated by Django 4.1 on 2023-03-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0043_alter_approval_authority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval_authority',
            options={'verbose_name': 'Approval Authorizer(Requisition)'},
        ),
    ]
