# Generated by Django 4.1 on 2023-03-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0044_alter_approval_authority_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval_authority',
            options={'verbose_name': 'Requisition Authorizer'},
        ),
    ]
