# Generated by Django 4.1 on 2023-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0045_alter_approval_authority_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
