# Generated by Django 4.1 on 2023-03-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('I_CARE', '0046_alter_requisition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='Placeholder',
            field=models.ForeignKey(db_column='Placeholer', default=1, on_delete=django.db.models.deletion.CASCADE, to='I_CARE.user_details'),
            preserve_default=False,
        ),
    ]
